language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

services:
  - docker

after_script:
  - docker build -t wnghd94/api:0.0.9 ./subprojects/api
  - docker build -t wnghd94/grpc:0.0.9 ./subprojects/grpc
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker push wnghd94/api:${TRAVIS_TAG}
  - docker push wnghd94/grpc:${TRAVIS_TAG}

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - derek@socar.kr